import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Film, FolderOpen, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { Project } from '@/types/database';
import { StatusBadge } from '@/components/StatusBadge';
import { LoadingSpinner } from '@/components/LoadingSpinner';

export function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('all');
  const [loading, setLoading] = useState(true);
  useEffect(() => { supabase.from('projects').select('*').order('created_at', { ascending: false }).then(({ data }) => { setProjects((data || []) as Project[]); setLoading(false); }); }, []);
  const filtered = projects.filter((p) => (status === 'all' || p.status === status) && `${p.title} ${p.idea} ${p.niche}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="animate-fade-in space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold tracking-tight text-ink-900">Projects</h2><p className="mt-1 text-sm text-ink-500">Every idea in your content pipeline.</p></div><Link to="/create" className="btn-primary"><Plus size={17} /> New project</Link></div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search projects…" className="input pl-9" /></div><div className="relative"><SlidersHorizontal size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-400" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="input w-full pl-9 sm:w-48"><option value="all">All statuses</option><option value="draft">Draft</option><option value="ready">Ready</option><option value="scheduled">Scheduled</option><option value="published">Published</option></select></div></div>{loading ? <div className="flex h-60 items-center justify-center"><LoadingSpinner /></div> : filtered.length === 0 ? <div className="card flex flex-col items-center justify-center px-6 py-20 text-center"><div className="mb-4 flex h-14 w-14 items-center justify-center rounded-xl bg-ink-100 text-ink-400"><FolderOpen size={25} /></div><h3 className="font-semibold text-ink-800">{projects.length ? 'No matching projects' : 'Your project library is empty'}</h3><p className="mt-1 max-w-sm text-sm text-ink-400">{projects.length ? 'Try adjusting your search or filters.' : 'Save a video idea to start building your content pipeline.'}</p>{!projects.length && <Link to="/create" className="btn-primary mt-5"><Plus size={16} /> Create project</Link>}</div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((p) => <Link to={`/projects/${p.id}`} key={p.id} className="card group p-5 transition-all hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Film size={20} /></div><StatusBadge status={p.status} /></div><h3 className="mt-5 line-clamp-2 font-semibold text-ink-900 group-hover:text-brand-700">{p.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-5 text-ink-500">{p.idea}</p><div className="mt-5 flex items-center justify-between border-t border-ink-100 pt-4 text-xs text-ink-400"><span>{p.niche}</span><span>{p.duration_seconds}s</span></div></Link>)}</div>}</div>;
}
